export enum BusinessCategory {
  TECHNOLOGY = 'Technology',
  MISC = 'Miscellaneous',
  RESTAURANT = 'Restaurant',
  GROCERY = 'Supermarket',
  PHARMACY = 'Pharmacy',
  ELECTRONICS = 'Electronics',
  FURNITURE = 'Furniture',
  BOOKS = 'Bookstore',
  GAMES = 'Video Games',
  PET_SUPPLIES = 'Pet Supplies',
  CLOTHING = 'Clothing',
  SHOES = 'Shoes',
  HOME_APPLIANCES = 'Home Appliances',
  TOYS = 'Toys',
  SPORTS = 'Sports',
  MUSIC = 'Music',
  ART = 'Art',
  BEAUTY = 'Beauty',
  HEALTH = 'Health',
  RETAIL = 'Retail',
  OTHER = 'Other',
}
