export enum BusinessCategory {
  MISC = 'Miscelánea',
  //   RESTAURANT = 'Restaurante',
  //   GROCERY = 'Supermercado',
  //   PHARMACY = 'Farmacia',
  //   ELECTRONICS = 'Electrónicos',
  //   FURNITURE = 'Muebles',
  //   BOOKS = 'Librería',
  //   GAMES = 'Videojuegos',
  //   PET_SUPPLIES = 'Accesorios para mascotas',
  //   CLOTHING = 'Ropa',
  //   SHOES = 'Calzado',
  //   HOME_APPLIANCES = 'Electrodomesticos',
  //   TOYS = 'Juguetes',
  //   SPORTS = 'Deportes',
  //   MUSIC = 'Música',
  //   ART = 'Arte',
  BEAUTY = 'Belleza',
  //   HEALTH = 'Salud',
  //   OTHER = 'Otro',
}
