export enum ProductCategory {
  HAIR_CARE = 'Hair Care',
  E_COMMERCE = 'E-commerce',
  FINANCE = 'Finance',
  HEALTH = 'Health',
  BEAUTY = 'Beauty',
  FITNESS = 'Fitness',
  FOOD = 'Food',
  PETS = 'Pets',
  TOYS = 'Toys',
  HOME = 'Home',
  ELECTRONICS = 'Electronics',
  FURNITURE = 'Furniture',
  GARDENING = 'Gardening',
  AUTOMOTIVE = 'Automotive',
  BOOKS = 'Books',
  MUSIC = 'Music',
  MOVIES = 'Movies',
  GAMES = 'Games',
  ART = 'Art',
  COLLECTIBLES = 'Collectibles',
  TOOLS = 'Tools',
  OTHER = 'Other',
}
